I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/game_func.rpy", line 18, in script
    init -10 python:
  File "game/game_func.rpy", line 27, in <module>
    renpy.define_screen()
TypeError: __init__() takes at least 3 arguments (1 given)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/game_func.rpy", line 18, in script
    init -10 python:
  File "W:\GamePython\renpy-7.3.2-sdk\renpy\ast.py", line 914, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "W:\GamePython\renpy-7.3.2-sdk\renpy\python.py", line 2028, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/game_func.rpy", line 27, in <module>
    renpy.define_screen()
  File "W:\GamePython\renpy-7.3.2-sdk\renpy\display\screen.py", line 982, in define_screen
    Screen(*args, **kwargs)
TypeError: __init__() takes at least 3 arguments (1 given)

Windows-8-6.2.9200
Ren'Py 7.3.5.606
 
Sat Feb 01 09:46:57 2020
